# Generated by Django 6.1.1 on 2026-09-23 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('efd18e3d-c815-4f39-a028-089d140da0f3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
