# Generated by Django 6.1.1 on 2026-09-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapps', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
