# Generated by Django 6.1.1 on 2026-09-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapps', '0006_profile_email_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
