# Generated by Django 6.1.1 on 2026-09-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapps', '0007_remove_profile_email_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
